# Change these first
owner: apgyorfi # Your GitHub organization or username, where this repository lives
repo: services-monitor # The name of this repository

runner: "[self-hosted, linux, X64]"
#skipDeleteIssues: true

sites:
  - name: Honlap
    url: https://apgyorfi.dev
  - name: ISP
    url: $ISP
  - name: Coolify 
    url: $COOLIFY
  - name: Dashy
    url: $DASHY
  - name: AUTH
    url: $AUTH
  - name: BKK API
    url: $BKKAPI
  - name: BM API
    url: $BM_API
  - name: Nextcloud
    url: $NEXTCLOUD

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.apgyorfi.dev
  # baseUrl: /services-monitor
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: apgyorfi.dev Status Page
  theme: ocean
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

commitMessages:
  commitAuthorName: "monitor-bot"
  commitAuthorEmail: $AUTHORMAIL

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
